### ISSUE TITLE
too many sockets open in forwarder

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#1039]
````
2016-11-10 02:40:25,359 (forwarderagent-3.6 2892) <stderr> ERROR: Exception AttributeError: "'NoneType' object has no attribute 'set'" in <bound method Socket.__del__ of <volttron.platform.vip.green.Socket object at 0x7eff88a17ae0>> igno
red
2016-11-10 02:40:25,438 (forwarderagent-3.6 2892) <stderr> ERROR: Traceback (most recent call last):
2016-11-10 02:40:25,439 (forwarderagent-3.6 2892) <stderr> ERROR:   File "/home/volttron/volttron-develop/env/local/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
2016-11-10 02:40:25,525 (forwarderagent-3.6 2892) <stderr> ERROR:     result = self._run(*self.args, **self.kwargs)
2016-11-10 02:40:25,526 (forwarderagent-3.6 2892) <stderr> ERROR:   File "/home/volttron/volttron-develop/volttron/platform/vip/agent/core.py", line 283, in run
2016-11-10 02:40:25,556 (forwarderagent-3.6 2892) <stderr> ERROR:     looper.next()
2016-11-10 02:40:25,557 (forwarderagent-3.6 2892) <stderr> ERROR:   File "/home/volttron/volttron-develop/volttron/platform/vip/agent/core.py", line 562, in loop
2016-11-10 02:40:25,557 (forwarderagent-3.6 2892) <stderr> ERROR:     self.socket = vip.Socket(self.context)
2016-11-10 02:40:25,557 (forwarderagent-3.6 2892) <stderr> ERROR:   File "/home/volttron/volttron-develop/volttron/platform/vip/socket.py", line 303, in __new__
2016-11-10 02:40:25,572 (forwarderagent-3.6 2892) <stderr> ERROR:     return base.__new__(cls, context, socket_type)
2016-11-10 02:40:25,573 (forwarderagent-3.6 2892) <stderr> ERROR:   File "zmq/backend/cython/socket.pyx", line 281, in zmq.backend.cython.socket.Socket.__cinit__ (zmq/backend/cython/socket.c:3220)
2016-11-10 02:40:25,592 (forwarderagent-3.6 2892) <stderr> ERROR: ZMQError: Too many open files
2016-11-10 02:40:25,592 (forwarderagent-3.6 2892) <stderr> ERROR: <Greenlet at 0x7eff88d585f0: <bound method Core.run of <volttron.platform.vip.agent.core.Core object at 0x7eff886fa1d0>>> failed with ZMQError
2016-11-10 02:40:25,592 (forwarderagent-3.6 2892) <stderr> ERROR: 
2016-11-10 02:40:35,369 (forwarderagent-3.6 2892) <stderr> ERROR: Traceback (most recent call last):
2016-11-10 02:40:35,369 (forwarderagent-3.6 2892) <stderr> ERROR:   File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
2016-11-10 02:40:35,369 (forwarderagent-3.6 2892) <stderr> ERROR:     msg = self.format(record)
2016-11-10 02:40:35,370 (forwarderagent-3.6 2892) <stderr> ERROR:   File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
2016-11-10 02:40:35,370 (forwarderagent-3.6 2892) <stderr> ERROR:     return fmt.format(record)
2016-11-10 02:40:35,370 (forwarderagent-3.6 2892) <stderr> ERROR:   File "/home/volttron/volttron-develop/volttron/platform/agent/utils.py", line 303, in format
2016-11-10 02:40:35,397 (forwarderagent-3.6 2892) <stderr> ERROR:     return jsonapi.dumps(dct)
2016-11-10 02:40:35,397 (forwarderagent-3.6 2892) <stderr> ERROR:   File "/home/volttron/volttron-develop/env/local/lib/python2.7/site-packages/zmq/utils/jsonapi.py", line 40, in dumps
2016-11-10 02:40:35,397 (forwarderagent-3.6 2892) <stderr> ERROR:     s = jsonmod.dumps(o, **kwargs)
2016-11-10 02:40:35,398 (forwarderagent-3.6 2892) <stderr> ERROR:   File "/home/volttron/volttron-develop/env/local/lib/python2.7/site-packages/simplejson/__init__.py", line 397, in dumps
2016-11-10 02:40:35,398 (forwarderagent-3.6 2892) <stderr> ERROR:     **kw).encode(obj)
2016-11-10 02:40:35,399 (forwarderagent-3.6 2892) <stderr> ERROR:   File "/home/volttron/volttron-develop/env/local/lib/python2.7/site-packages/simplejson/encoder.py", line 275, in encode
2016-11-10 02:40:35,461 (forwarderagent-3.6 2892) <stderr> ERROR:     chunks = self.iterencode(o, _one_shot=True)
2016-11-10 02:40:35,461 (forwarderagent-3.6 2892) <stderr> ERROR:   File "/home/volttron/volttron-develop/env/local/lib/python2.7/site-packages/simplejson/encoder.py", line 357, in iterencode
2016-11-10 02:40:35,461 (forwarderagent-3.6 2892) <stderr> ERROR:     return _iterencode(o, 0)
2016-11-10 02:40:35,462 (forwarderagent-3.6 2892) <stderr> ERROR:   File "/home/volttron/volttron-develop/env/local/lib/python2.7/site-packages/simplejson/encoder.py", line 252, in default
2016-11-10 02:40:35,462 (forwarderagent-3.6 2892) <stderr> ERROR:     raise TypeError(repr(o) + " is not JSON serializable")
2016-11-10 02:40:35,463 (forwarderagent-3.6 2892) <stderr> ERROR: TypeError: AttributeError("'NoneType' object has no attribute 'call'",) is not JSON serializable
2016-11-10 02:40:35,463 (forwarderagent-3.6 2892) <stderr> ERROR: Logged from file agent.py, line 279
````

**Comment by schandrika** [comment]
Fixed with PR #1359
