### ISSUE TITLE
Forward historian stack trace when to platform is unavailable. (I think!)

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#1040]
2016-11-10 21:33:21,029 (forwarderagent-3.6 24626) forwarder.agent ERROR: A timeout has occured so breaking out of publishing
2016-11-10 21:33:21,030 (forwarderagent-3.6 24626) volttron.platform.agent.base_historian ERROR: An unhandled exception occured while publishing.
Traceback (most recent call last):
  File "/home/volttron/volttron-develop/volttron/platform/agent/base_historian.py", line 679, in _process_loop
    self.publish_to_historian(to_publish_list)
  File "/home/volttron/.volttron_10500/agents/0abaafe5-076e-406a-b8fc-8de4fc2e60e3/forwarderagent-3.6/forwarder/agent.py", line 289, in publish_to_historian
    status = Status.from_json(self.vip.health.get_status())
  File "/home/volttron/volttron-develop/volttron/platform/messaging/health.py", line 121, in from_json
    cp = jsonapi.loads(data)
  File "/home/volttron/volttron-develop/env/local/lib/python2.7/site-packages/zmq/utils/jsonapi.py", line 56, in loads
    return jsonmod.loads(s, **kwargs)
  File "/home/volttron/volttron-develop/env/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/volttron/volttron-develop/env/local/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/volttron/volttron-develop/env/local/lib/python2.7/site-packages/simplejson/decoder.py", line 395, in raw_decode
    ord0 = ord(s[idx])
KeyError: 0

**Comment by schandrika** [comment]
@schandrika  to test
