### ISSUE TITLE
Better handling of shutdown platform.

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#113]
This output is observered when runinnt the command volttron-ctl shutdown --platform.

Traceback (most recent call last):
  File "gevent/core.pyx", line 348, in gevent.core.loop.handle_error (gevent/gevent.core.c:6053)
  File "/home/dev/git/volttron/env/local/lib/python2.7/site-packages/gevent/hub.py", line 300, in handle_error
    self.print_exception(context, type, value, tb)
  File "/home/dev/git/volttron/env/local/lib/python2.7/site-packages/gevent/hub.py", line 323, in print_exception
    traceback.print_exception(type, value, tb)
AttributeError: 'NoneType' object has no attribute 'print_exception'

**Comment by hashstat** [comment]
Have you experienced this error again? Looking at the line in question, it states that the variable `traceback` is `None`, but `traceback` is a module imported at the top of the `hub` module and the only way I would expect it to be None is if it was accidentally set to None in another module. If you can repeat the error, then let's have a look at it together to find the cause.
