### ISSUE TITLE
Handle registration of web endpoints better

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#1344]
Currently if a platform hasn't been "web enabled" the following trace will happen without really providing the context to fix the issue.

````
2017-05-04 17:27:20,836 () volttron.platform.web DEBUG: REGISTERING ENDPOINT: /vc/ws
2017-05-04 17:27:20,836 () volttron.platform.vip.agent.subsystems.rpc ERROR: unhandled exception in JSON-RPC method 'register_websocket': 
Traceback (most recent call last):
  File "/opt/volttron/volttron/volttron/platform/vip/agent/subsystems/rpc.py", line 168, in method
    return method(*args, **kwargs)
  File "/opt/volttron/volttron/volttron/platform/web.py", line 497, in register_websocket
    self.appContainer.create_ws_endpoint(endpoint, identity)
AttributeError: 'NoneType' object has no attribute 'create_ws_endpoint'
````

The only way this happens is when the platform hasn't been started with a web address.

**Comment by acedrew** [comment]
What were the steps for recreating this?
