### ISSUE TITLE
SQLite Historian Lock error

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#143]
Historian db lock error:

Traceback (most recent call last):
  File "/home/rtu/git/volttron/volttron/platform/vip/agent/subsystems/rpc.py", line 168, in method
    return method(*args, **kwargs)
  File "/home/rtu/.volttron/agents/167ca709-93e7-488b-a38e-ad248d6e11e1/platformagentagent-0.1/platformagent/agent.py", line 340, in route_request
    **params).get()
  File "/home/rtu/git/volttron/env/local/lib/python2.7/site-packages/gevent/event.py", line 242, in get
    raise self._exception
RemoteError: sqlite3.OperationalError('database is locked')

On restart of historian:

2015-08-05 13:34:58,353 (sqlhistorianagent-0.1 29516) <stderr> ERROR: Exception in thread Thread-2:
2015-08-05 13:34:58,353 (sqlhistorianagent-0.1 29516) <stderr> ERROR: Traceback (most recent call last):
2015-08-05 13:34:58,354 (sqlhistorianagent-0.1 29516) <stderr> ERROR:   File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
2015-08-05 13:34:58,354 (sqlhistorianagent-0.1 29516) <stderr> ERROR:     self.run()
2015-08-05 13:34:58,354 (sqlhistorianagent-0.1 29516) <stderr> ERROR:   File "/usr/lib/python2.7/threading.py", line 505, in run
2015-08-05 13:34:58,354 (sqlhistorianagent-0.1 29516) <stderr> ERROR:     self.__target(*self.__args, **self.__kwargs)
2015-08-05 13:34:58,354 (sqlhistorianagent-0.1 29516) <stderr> ERROR:   File "/home/rtu/git/volttron/volttron/platform/agent/base_historian.py", line 339, in _process_loop
2015-08-05 13:34:58,354 (sqlhistorianagent-0.1 29516) <stderr> ERROR:     self.publish_to_historian(to_publish_list)
2015-08-05 13:34:58,355 (sqlhistorianagent-0.1 29516) <stderr> ERROR:   File "/home/rtu/.volttron/agents/7579eea0-0e80-4974-90a0-13989b4f21e2/sqlhistorianagent-0.1/sqlhistorian/historian.py", line 170, in publish_to_historian
2015-08-05 13:34:58,355 (sqlhistorianagent-0.1 29516) <stderr> ERROR:     self.writer.insert_data(ts,topic_id, value)
2015-08-05 13:34:58,355 (sqlhistorianagent-0.1 29516) <stderr> ERROR:   File "/home/rtu/.volttron/agents/7579eea0-0e80-4974-90a0-13989b4f21e2/sqlhistorianagent-0.1/sqlhistorian/db/sqlitefuncts.py", line 195, in insert_data
2015-08-05 13:34:58,355 (sqlhistorianagent-0.1 29516) <stderr> ERROR:     self.conn.commit()
2015-08-05 13:34:58,355 (sqlhistorianagent-0.1 29516) <stderr> ERROR: OperationalError: database is locked
2015-08-05 13:34:58,355 (sqlhistorianagent-0.1 29516) <stderr> ERROR:

**Comment by jhaack** [comment]
Fixed
