### ISSUE TITLE
Unable to edit/create non-existing config store file

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#1446]
The following command was run and produced an error:

````
(volttron)volttron@volttron-VirtualBox ~/git/volttron $ vctl config edit platform.agent configconfig: error: 'No configuration file "config" for VIP IDENTIY platform.agent'
````
I would have expected the behavior to simply start editing a file that would later be saved to the config store.  

The following error on the platform was observed:

````
2017-08-17 19:24:15,170 () volttron.platform.vip.agent.subsystems.rpc ERROR: unhandled exception in JSON-RPC method 'manage_get_metadata': 
Traceback (most recent call last):
  File "/home/volttron/git/volttron/volttron/platform/vip/agent/subsystems/rpc.py", line 169, in method
    return method(*args, **kwargs)
  File "/home/volttron/git/volttron/volttron/platform/store.py", line 256, in manage_get_metadata
    raise KeyError('No configuration file "{}" for VIP IDENTIY {}'.format(config_name, identity))
KeyError: 'No configuration file "config" for VIP IDENTIY platform.agent'
````

**Comment by kmonson** [comment]
The fix won't get rid of the Exception on the platform side. That is a natural result of trying to get info on a config that doesn't exist.
