### ISSUE TITLE
Bootstrap fails on virtualenv url due to http

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#1681]
NOTE issues are for bugs/feature requests not support.  Please ask at https://stackoverflow.com/questions/tagged/volttron for help

### Description of Issue

Bootstrap fails on virtualenv, line 169. Change url to https from http fixes the problem

### Affected Version
All 
### Steps to Reproduce
Remove env, attempt bootstrap
### Additional Details
Creating virtual Python environment
Downloading virtualenv DOAP record
Traceback (most recent call last):
  File "bootstrap.py", line 383, in <module>
    main()
  File "bootstrap.py", line 366, in main
    options.force_version, options.verbose)
  File "bootstrap.py", line 187, in bootstrap
    builder.create(dest, verbose)
  File "bootstrap.py", line 165, in create
    self.download(tmpdir)
  File "bootstrap.py", line 150, in download
    self.get_version()
  File "bootstrap.py", line 141, in get_version
    with contextlib.closing(self._fetch(doap_url)) as response:
  File "bootstrap.py", line 128, in _fetch
    response = urllib2.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 410: DOAP is no longer supported.

**Comment by jhaack** [comment]
Duplicate of #1679
