### ISSUE TITLE
Errors in log when volttron-ctl stop is used

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#172]
The following logging was created when I chose to stop an agent using volttron-ctl.  It seems to me that this output shouldn't be generated for a "normal" agent stop, but should be reserved for when something actually breaks.

@hashstat @jhaack  do you have any opinion on this?

```
2015-09-04 13:39:45,682 (datapublisher-0.1 30243) <stderr> ERROR: KeyboardInterrupt
2015-09-04 13:39:45,682 (datapublisher-0.1 30243) <stderr> ERROR: Traceback (most recent call last):
2015-09-04 13:39:45,682 (datapublisher-0.1 30243) <stderr> ERROR:   File "/home/volttron/git/volttron/env/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
2015-09-04 13:39:45,683 (datapublisher-0.1 30243) <stderr> ERROR:     result = self._run(*self.args, **self.kwargs)
2015-09-04 13:39:45,684 (datapublisher-0.1 30243) <stderr> ERROR:   File "/home/volttron/git/volttron/volttron/platform/vip/agent/core.py", line 258, in run
2015-09-04 13:39:45,684 (datapublisher-0.1 30243) <stderr> ERROR:     self.onfinish.send(self)
2015-09-04 13:39:45,685 (datapublisher-0.1 30243) <stderr> ERROR:   File "/home/volttron/git/volttron/volttron/platform/vip/agent/dispatch.py", line 82, in send
2015-09-04 13:39:45,685 (datapublisher-0.1 30243) <stderr> ERROR:     for receiver in self._receivers]
2015-09-04 13:39:45,685 (datapublisher-0.1 30243) <stderr> ERROR: TypeError: finish() takes exactly 1 argument (2 given)
2015-09-04 13:39:45,686 (datapublisher-0.1 30243) <stderr> ERROR: <Greenlet at 0x7f05ba8a0370: <bound method Core.run of <volttron.platform.vip.agent.core.Core object at 0x7f05ba610e50>>> failed with TypeError
2015-09-04 13:39:45,686 (datapublisher-0.1 30243) <stderr> ERROR: 
2015-09-04 13:39:45,686 (datapublisher-0.1 30243) <stderr> ERROR: Traceback (most recent call last):
2015-09-04 13:39:45,695 (datapublisher-0.1 30243) <stderr> ERROR:   File "<string>", line 1, in <module>
2015-09-04 13:39:45,695 (datapublisher-0.1 30243) <stderr> ERROR:   File "/home/volttron/.volttron/agents/dd81bfe7-1181-4ba5-8b59-3f221fafe41e/datapublisher-0.1/datapublisher/publisher3.py", line 384, in main
2015-09-04 13:39:45,695 (datapublisher-0.1 30243) <stderr> ERROR:     utils.vip_main(DataPub)
2015-09-04 13:39:45,696 (datapublisher-0.1 30243) <stderr> ERROR:   File "/home/volttron/git/volttron/volttron/platform/agent/utils.py", line 207, in vip_main
2015-09-04 13:39:45,696 (datapublisher-0.1 30243) <stderr> ERROR:     task.join()
2015-09-04 13:39:45,696 (datapublisher-0.1 30243) <stderr> ERROR:   File "/home/volttron/git/volttron/env/local/lib/python2.7/site-packages/gevent/greenlet.py", line 290, in join
2015-09-04 13:39:45,696 (datapublisher-0.1 30243) <stderr> ERROR:     result = self.parent.switch()
2015-09-04 13:39:45,697 (datapublisher-0.1 30243) <stderr> ERROR:   File "/home/volttron/git/volttron/env/local/lib/python2.7/site-packages/gevent/hub.py", line 338, in switch
2015-09-04 13:39:45,697 (datapublisher-0.1 30243) <stderr> ERROR:     return greenlet.switch(self)
2015-09-04 13:39:45,697 (datapublisher-0.1 30243) <stderr> ERROR: KeyboardInterrupt
```

**Comment by jhaack** [comment]
OBE
