### ISSUE TITLE
Unable to run the script file (volttron/scripts/management-service-demo/run-demo)

### ISSUE THREAD

**Issue by sumanth13** [VOLTTRON/volttron#189]
Whenever I try to run this scrpit then a terminal pops up and closes automatically without any display. Can someone help me with this issue?

**Comment by hashstat** [comment]
I would be happy to help. I haven't run that script before, so I can't give a flippant "it works on my system" answer*. At least not yet. :wink:

<sub>* This comment is an attempt at humor and in no way should be taken to indicate that anyone on the VOLTTRON team would actually provide a flippant answer.</sub>

**Comment by hashstat** [comment]
@sumanth13, can you provide some more detail about how you run the script? Is there a guide/wiki page you are following? What is the exact command you execute? Are you doing that in a terminal with VOLTTRON activated?

Let me know the steps to repeat so that I can provide you quick and accurate feedback. Thanks.

**Comment by sumanth13** [comment]
When I searched how to run a .sh file I found two ways
1) By making the file executable and then double clicking on it.
2) Running the file in terminal i.e., sh <filename>.sh

The above mentioned issue is when I tried to first way. 
When I tried the second way by activating volttron it says: Please execute from root of volttron repository.

**Comment by hashstat** [comment]
Yeah. The problem with (1) is that it launches the terminal and, unless the terminal is configured otherwise, it closes after execution providing no opportunity to examine the output. The script is designed to be run from an activated shell. Open a terminal and do the following:

```
~$ cd $VOLTTRON_HOME
volttron$ . env/bin/activate
(volttron) volttron$ bash scripts/management-service-demo/run-demo.sh
```

Replace $VOLTTRON_HOME with the path where you checked out the VOLTTRON repository.

**Comment by sumanth13** [comment]
Now I am able to run the file and launch the browser but there is a problem
is loading the page. I am sending the screen shot of the browser.

​

*Thanks & Regards,*
*Nallabolu Sumanth Reddy*
*Electrical and Computer Engineering,*
*Michigan Technological University,*
*Houghton,MI-49931.*

**Comment by craig8** [comment]
ok so from the terminal can you exectute the comman
    VOLTTRON_HOME=/tmp/v1home volttron-ctl status

This should show the status of the agents on the 1st volttron instance.  There are 3 instances v1home, v2home, and v3home created when you run the demo script.  You should see agents in a running state.

**Comment by hashstat** [comment]
> Now I am able to run the file and launch the browser but there is a problem is loading the page. I am sending the screen shot of the browser.

@sumanth13, it looks like you replied via an email client and the screenshot did not make it through. @craig8 believes the problem your are now experiencing might be due to other instances of volttron running. If you don't mind killing them, try `pkill volttron` and run the script again. If this doesn't help, please attach your screenshot using Github's issues interface rather than replying via your email client. Thanks.

**Comment by sumanth13** [comment]
When I tried the above command (volttron-ctl status) it waits for some 20-30 seconds and then displays: status: operation timed out. I tried pkill volttron also but the result is same. I am sending screenshots
![in tmp](https://cloud.githubusercontent.com/assets/14006782/10210154/609e09de-67b1-11e5-9f03-4e9276a6080f.png)
![in_volttron](https://cloud.githubusercontent.com/assets/14006782/10210153/609dd414-67b1-11e5-8b54-309055d6f9fd.png)
![unable to connect](https://cloud.githubusercontent.com/assets/14006782/10210152/609c6354-67b1-11e5-87a5-fecf462eb0ef.png)
![screenshot from 2015-09-30 19 55 13](https://cloud.githubusercontent.com/assets/14006782/10210161/793d227c-67b1-11e5-989b-e4a1d2150f30.png)



 so that you can understand the issue more clearly

**Comment by sumanth13** [comment]
One of my friends is also trying the same thing. He found that the script file is running well in linux mint but was unable to do it in ubuntu12.04.

**Comment by craig8** [comment]
In order to use the volttron instances that are created with the demo script you must prefix it with the VOLTTRON_HOME variable.

    VOLTTRON_HOME=/tmp/v1home volttron-ctl status

Note that this is not the same thing as

    volttron-ctl status

which is what I see you have entered in your shell.  The one you entered is attempting to contact a default instance of volttron with the VOLTTRON_HOME set to $HOME/.volttron.  As you are running the demo script that instance is not available.

In otherwords, you will use volttron-ctl without a VOLTTRON_HOME when you are running a default volttron e.g. if you started volttron like

    volttron -vv -l volttron.log& 

then you could do a 

    volttron-ctl status

and you should receive a response.

I hope this helps.

**Comment by craig8** [comment]
One other thing.  In your images I don't see volttroncentral agent as one of the ones that was started.  I assume this is because it is further up on the command window buffer.  The volttroncentral agent is what is responsible for starting the webserver.

**Comment by sumanth13** [comment]
![1](https://cloud.githubusercontent.com/assets/14006782/10210605/08d42192-67b7-11e5-8e74-884ced77aeb9.png)

**Comment by sumanth13** [comment]
Above is what I got when I run check the status

**Comment by craig8** [comment]
Awesome...so that means that the vc errored out or something happened.  You can try restarting it with the command

    VOLTTRON_HOME/tmp/v1home volttron-ctl start --tag vc

if after running the above status again after that then please upload the log file located at /tmp/v1home/volttron.log

From that I should be able to see what is going on (hopefully).  Also, I don't see in this thread which branch you have checked out from.  3.x or master?

Thanks

**Comment by sumanth13** [comment]
2015-09-30 22:20:35,778 () volttron.platform.main DEBUG: open file resource limit increased from 1024 to 4096
2015-09-30 22:20:35,778 () volttron.platform.main WARNING: insecure mode on directory: /tmp/v1home
2015-09-30 22:20:35,779 () volttron.platform.main DEBUG: using key file /tmp/v1home/curve.key
2015-09-30 22:20:35,779 () volttron.platform.main WARNING: insecure mode on key file
2015-09-30 22:20:35,779 () volttron.platform.main WARNING: empty key file; VIP encryption is disabled!
2015-09-30 22:20:35,784 () volttron.platform.main ERROR: Unhandled exception in router loop
Traceback (most recent call last):
  File "/home/sumanth/Desktop/V3/volttron-3.x/volttron/platform/main.py", line 573, in router
    monitor=opts.monitor).run()
  File "/home/sumanth/Desktop/V3/volttron-3.x/volttron/platform/main.py", line 271, in run
    self.start()
  File "/home/sumanth/Desktop/V3/volttron-3.x/volttron/platform/vip/router.py", line 120, in start
    self.setup()
  File "/home/sumanth/Desktop/V3/volttron-3.x/volttron/platform/main.py", line 257, in setup
    sock.bind(self.local_address)
  File "zmq/backend/cython/socket.pyx", line 489, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:4824)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7055)
    raise ZMQError(errno)
ZMQError: Address already in use
2015-09-30 22:20:37,050 () volttron.platform.auth INFO: 'vip' 'localhost:1002:1002:9111' 'NULL' []
2015-09-30 22:20:37,053 () volttron.platform.aip INFO: starting agent /tmp/v1home/agents/de49899b-362b-405c-8526-7d22c19495c1/volttroncentralagent-0.1
2015-09-30 22:20:37,058 () volttron.platform.aip INFO: agent /tmp/v1home/agents/de49899b-362b-405c-8526-7d22c19495c1/volttroncentralagent-0.1 has PID 9129
2015-09-30 22:20:37,264 (volttroncentralagent-0.1 9129) <stderr> ERROR: Traceback (most recent call last):
2015-09-30 22:20:37,264 (volttroncentralagent-0.1 9129) <stderr> ERROR:   File "<string>", line 1, in <module>
2015-09-30 22:20:37,264 (volttroncentralagent-0.1 9129) <stderr> ERROR:   File "/tmp/v1home/agents/de49899b-362b-405c-8526-7d22c19495c1/volttroncentralagent-0.1/volttroncentral/vc.py", line 78, in <module>
2015-09-30 22:20:37,264 (volttroncentralagent-0.1 9129) <stderr> ERROR:     from volttron.platform.async import AsyncCall
2015-09-30 22:20:37,264 (volttroncentralagent-0.1 9129) <stderr> ERROR:   File "/home/sumanth/Desktop/V3/volttron-3.x/volttron/platform/async.py", line 78, in <module>
2015-09-30 22:20:37,264 (volttroncentralagent-0.1 9129) <stderr> ERROR:     class Threadlet(threading.Thread):
2015-09-30 22:20:37,264 (volttroncentralagent-0.1 9129) <stderr> ERROR:   File "/home/sumanth/Desktop/V3/volttron-3.x/volttron/platform/async.py", line 111, in Threadlet
2015-09-30 22:20:37,264 (volttroncentralagent-0.1 9129) <stderr> ERROR:     __init__.__doc__ = threading.Thread.__init__.__doc__ + __init__.__doc__
2015-09-30 22:20:37,264 (volttroncentralagent-0.1 9129) <stderr> ERROR: TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2015-09-30 22:20:38,476 () volttron.platform.auth INFO: 'vip' 'localhost:1002:1002:9210' 'NULL' []
2015-09-30 22:20:38,479 () volttron.platform.aip INFO: starting agent /tmp/v1home/agents/ca5e2b94-41b9-463c-8f39-67322082e7ef/platformagentagent-0.1
2015-09-30 22:20:38,484 () volttron.platform.aip INFO: agent /tmp/v1home/agents/ca5e2b94-41b9-463c-8f39-67322082e7ef/platformagentagent-0.1 has PID 9228
2015-09-30 22:20:38,701 (platformagentagent-0.1 9228) platformagent.agent INFO: my identity platform.agent address: ipc://@/tmp/v1home/run/vip.socket
2015-09-30 22:20:38,701 (platformagentagent-0.1 9228) platformagent.agent DEBUG: Exception 
2015-09-30 22:20:38,706 (platformagentagent-0.1 9228) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:20:38,707 () volttron.platform.auth INFO: 'vip' 'localhost:1002:1002:9228' 'NULL' []
2015-09-30 22:20:38,743 () volttron.platform.auth INFO: 'vip' 'localhost:1002:1002:9233' 'NULL' []
2015-09-30 22:20:41,710 (platformagentagent-0.1 9228) <stderr> ERROR: Traceback (most recent call last):
2015-09-30 22:20:41,710 (platformagentagent-0.1 9228) <stderr> ERROR:   File "/home/sumanth/Desktop/V3/volttron-3.x/env/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
2015-09-30 22:20:41,710 (platformagentagent-0.1 9228) <stderr> ERROR:     result = self._run(*self.args, **self.kwargs)
2015-09-30 22:20:41,710 (platformagentagent-0.1 9228) <stderr> ERROR:   File "/tmp/v1home/agents/ca5e2b94-41b9-463c-8f39-67322082e7ef/platformagentagent-0.1/platformagent/agent.py", line 384, in starting
2015-09-30 22:20:41,710 (platformagentagent-0.1 9228) <stderr> ERROR:     _, _, my_id = self.vip.hello().get(timeout=3)
2015-09-30 22:20:41,710 (platformagentagent-0.1 9228) <stderr> ERROR:   File "/home/sumanth/Desktop/V3/volttron-3.x/env/local/lib/python2.7/site-packages/gevent/event.py", line 233, in get
2015-09-30 22:20:41,711 (platformagentagent-0.1 9228) <stderr> ERROR:     result = self.hub.switch()
2015-09-30 22:20:41,711 (platformagentagent-0.1 9228) <stderr> ERROR:   File "/home/sumanth/Desktop/V3/volttron-3.x/env/local/lib/python2.7/site-packages/gevent/hub.py", line 338, in switch
2015-09-30 22:20:41,711 (platformagentagent-0.1 9228) <stderr> ERROR:     return greenlet.switch(self)
2015-09-30 22:20:41,711 (platformagentagent-0.1 9228) <stderr> ERROR: Timeout: 3 seconds
2015-09-30 22:20:41,711 (platformagentagent-0.1 9228) <stderr> ERROR: <Greenlet at 0x32805f0: <bound method PlatformAgent.starting of <platformagent.agent.PlatformAgent object at 0x32871d0>>(<volttron.platform.vip.agent.core.Core object at 0)> failed with Timeout
2015-09-30 22:20:41,711 (platformagentagent-0.1 9228) <stderr> ERROR: 
2015-09-30 22:20:42,995 () volttron.platform.auth INFO: 'vip' 'localhost:1002:1002:9558' 'NULL' []
2015-09-30 22:20:42,998 () volttron.platform.aip INFO: starting agent /tmp/v1home/agents/11b4172e-f64b-4459-880b-8d43ff1b7600/sqlhistorianagent-0.1
2015-09-30 22:20:43,003 () volttron.platform.aip INFO: agent /tmp/v1home/agents/11b4172e-f64b-4459-880b-8d43ff1b7600/sqlhistorianagent-0.1 has PID 9576
2015-09-30 22:20:43,167 (sqlhistorianagent-0.1 9576) <stderr> ERROR: Generating LALR tables
2015-09-30 22:20:43,175 (sqlhistorianagent-0.1 9576) <stdout> INFO: Starting address: ipc://@/tmp/v1home/run/vip.socket identity: platform.historian
2015-09-30 22:20:43,175 (sqlhistorianagent-0.1 9576) volttron.platform.agent.base_historian DEBUG: Starting process loop.
2015-09-30 22:20:43,175 (sqlhistorianagent-0.1 9576) volttron.platform.agent.base_historian DEBUG: Setting up backup DB.
2015-09-30 22:20:43,176 (sqlhistorianagent-0.1 9576) volttron.platform.agent.base_historian DEBUG: Configuring backup BD for the first time.
2015-09-30 22:20:43,176 () volttron.platform.auth INFO: 'vip' 'localhost:1002:1002:9576' 'NULL' []
2015-09-30 22:20:43,537 (sqlhistorianagent-0.1 9576) volttron.platform.agent.base_historian DEBUG: Starting base historian
2015-09-30 22:20:43,537 (sqlhistorianagent-0.1 9576) volttron.platform.agent.base_historian DEBUG: subscribing to devices
2015-09-30 22:20:43,538 (sqlhistorianagent-0.1 9576) volttron.platform.agent.base_historian DEBUG: Subscribing to: datalogger
2015-09-30 22:20:43,538 (sqlhistorianagent-0.1 9576) volttron.platform.agent.base_historian DEBUG: Subscribing to: 
2015-09-30 22:20:43,538 (sqlhistorianagent-0.1 9576) volttron.platform.agent.base_historian DEBUG: Subscribing to: analysis
2015-09-30 22:20:43,722 (sqlhistorianagent-0.1 9576) volttron.platform.agent.base_historian DEBUG: Getting oldest outstanding to publish.
2015-09-30 22:20:43,722 (sqlhistorianagent-0.1 9576) volttron.platform.agent.base_historian DEBUG: Reading from/waiting for queue.
2015-09-30 22:20:45,166 (platformagentagent-0.1 7231) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:20:46,538 (sqlhistorianagent-0.1 9576) sqlhistorian.historian DEBUG: Listening to /platform
2015-09-30 22:20:46,539 (sqlhistorianagent-0.1 9576) <stderr> ERROR: Traceback (most recent call last):
2015-09-30 22:20:46,539 (sqlhistorianagent-0.1 9576) <stderr> ERROR:   File "/home/sumanth/Desktop/V3/volttron-3.x/env/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
2015-09-30 22:20:46,539 (sqlhistorianagent-0.1 9576) <stderr> ERROR:     result = self._run(*self.args, **self.kwargs)
2015-09-30 22:20:46,539 (sqlhistorianagent-0.1 9576) <stderr> ERROR:   File "/tmp/v1home/agents/11b4172e-f64b-4459-880b-8d43ff1b7600/sqlhistorianagent-0.1/sqlhistorian/historian.py", line 129, in starting
2015-09-30 22:20:46,539 (sqlhistorianagent-0.1 9576) <stderr> ERROR:     'awake?').get(timeout=3)
2015-09-30 22:20:46,540 (sqlhistorianagent-0.1 9576) <stderr> ERROR:   File "/home/sumanth/Desktop/V3/volttron-3.x/env/local/lib/python2.7/site-packages/gevent/event.py", line 233, in get
2015-09-30 22:20:46,540 (sqlhistorianagent-0.1 9576) <stderr> ERROR:     result = self.hub.switch()
2015-09-30 22:20:46,540 (sqlhistorianagent-0.1 9576) <stderr> ERROR:   File "/home/sumanth/Desktop/V3/volttron-3.x/env/local/lib/python2.7/site-packages/gevent/hub.py", line 338, in switch
2015-09-30 22:20:46,540 (sqlhistorianagent-0.1 9576) <stderr> ERROR:     return greenlet.switch(self)
2015-09-30 22:20:46,540 (sqlhistorianagent-0.1 9576) <stderr> ERROR: Timeout: 3 seconds
2015-09-30 22:20:46,540 (sqlhistorianagent-0.1 9576) <stderr> ERROR: <Greenlet at 0x119d550: <bound method SQLHistorian.starting of <sqlhistorian.historian.SQLHistorian object at 0x11df450>>(<volttron.platform.vip.agent.core.Core object at 0)> failed with Timeout
2015-09-30 22:20:46,540 (sqlhistorianagent-0.1 9576) <stderr> ERROR: 
2015-09-30 22:20:56,708 () volttron.platform.auth INFO: 'vip' 'localhost:1002:1002:9853' 'NULL' []
2015-09-30 22:21:08,711 (platformagentagent-0.1 9228) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:21:10,713 (platformagentagent-0.1 9228) <stderr> ERROR: Traceback (most recent call last):
2015-09-30 22:21:10,714 (platformagentagent-0.1 9228) <stderr> ERROR:   File "/home/sumanth/Desktop/V3/volttron-3.x/env/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
2015-09-30 22:21:10,714 (platformagentagent-0.1 9228) <stderr> ERROR:     result = self._run(*self.args, **self.kwargs)
2015-09-30 22:21:10,714 (platformagentagent-0.1 9228) <stderr> ERROR:   File "/home/sumanth/Desktop/V3/volttron-3.x/volttron/platform/vip/agent/core.py", line 114, in _loop
2015-09-30 22:21:10,714 (platformagentagent-0.1 9228) <stderr> ERROR:     method(*self.args, **self.kwargs)
2015-09-30 22:21:10,714 (platformagentagent-0.1 9228) <stderr> ERROR:   File "/tmp/v1home/agents/ca5e2b94-41b9-463c-8f39-67322082e7ef/platformagentagent-0.1/platformagent/agent.py", line 172, in write_status
2015-09-30 22:21:10,714 (platformagentagent-0.1 9228) <stderr> ERROR:     ping = self.vip.ping('platform.historian', 'awake?').get(timeout=2)
2015-09-30 22:21:10,714 (platformagentagent-0.1 9228) <stderr> ERROR:   File "/home/sumanth/Desktop/V3/volttron-3.x/env/local/lib/python2.7/site-packages/gevent/event.py", line 233, in get
2015-09-30 22:21:10,714 (platformagentagent-0.1 9228) <stderr> ERROR:     result = self.hub.switch()
2015-09-30 22:21:10,714 (platformagentagent-0.1 9228) <stderr> ERROR:   File "/home/sumanth/Desktop/V3/volttron-3.x/env/local/lib/python2.7/site-packages/gevent/hub.py", line 338, in switch
2015-09-30 22:21:10,714 (platformagentagent-0.1 9228) <stderr> ERROR:     return greenlet.switch(self)
2015-09-30 22:21:10,714 (platformagentagent-0.1 9228) <stderr> ERROR: Timeout: 2 seconds
2015-09-30 22:21:10,714 (platformagentagent-0.1 9228) <stderr> ERROR: <Greenlet at 0x3280370: <bound method Periodic._loop of <volttron.platform.vip.agent.core.Periodic object at 0x3287150>>(<bound method PlatformAgent.write_status of <platf)> failed with Timeout
2015-09-30 22:21:10,714 (platformagentagent-0.1 9228) <stderr> ERROR: 
2015-09-30 22:21:15,171 (platformagentagent-0.1 7231) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:21:26,053 () volttron.platform.auth INFO: 'vip' 'localhost:1002:1002:9872' 'NULL' []
2015-09-30 22:21:26,056 () volttron.platform.aip INFO: starting agent /tmp/v1home/agents/de49899b-362b-405c-8526-7d22c19495c1/volttroncentralagent-0.1
2015-09-30 22:21:26,061 () volttron.platform.aip INFO: agent /tmp/v1home/agents/de49899b-362b-405c-8526-7d22c19495c1/volttroncentralagent-0.1 has PID 9890
2015-09-30 22:21:26,243 (volttroncentralagent-0.1 9890) <stderr> ERROR: Traceback (most recent call last):
2015-09-30 22:21:26,243 (volttroncentralagent-0.1 9890) <stderr> ERROR:   File "<string>", line 1, in <module>
2015-09-30 22:21:26,243 (volttroncentralagent-0.1 9890) <stderr> ERROR:   File "/tmp/v1home/agents/de49899b-362b-405c-8526-7d22c19495c1/volttroncentralagent-0.1/volttroncentral/vc.py", line 78, in <module>
2015-09-30 22:21:26,243 (volttroncentralagent-0.1 9890) <stderr> ERROR:     from volttron.platform.async import AsyncCall
2015-09-30 22:21:26,243 (volttroncentralagent-0.1 9890) <stderr> ERROR:   File "/home/sumanth/Desktop/V3/volttron-3.x/volttron/platform/async.py", line 78, in <module>
2015-09-30 22:21:26,243 (volttroncentralagent-0.1 9890) <stderr> ERROR:     class Threadlet(threading.Thread):
2015-09-30 22:21:26,243 (volttroncentralagent-0.1 9890) <stderr> ERROR:   File "/home/sumanth/Desktop/V3/volttron-3.x/volttron/platform/async.py", line 111, in Threadlet
2015-09-30 22:21:26,243 (volttroncentralagent-0.1 9890) <stderr> ERROR:     __init__.__doc__ = threading.Thread.__init__.__doc__ + __init__.__doc__
2015-09-30 22:21:26,243 (volttroncentralagent-0.1 9890) <stderr> ERROR: TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2015-09-30 22:21:38,713 (platformagentagent-0.1 9228) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:21:45,172 (platformagentagent-0.1 7231) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:22:04,982 () volttron.platform.auth INFO: 'vip' 'localhost:1002:1002:9902' 'NULL' []
2015-09-30 22:22:04,984 () volttron.platform.aip INFO: starting agent /tmp/v1home/agents/de49899b-362b-405c-8526-7d22c19495c1/volttroncentralagent-0.1
2015-09-30 22:22:04,989 () volttron.platform.aip INFO: agent /tmp/v1home/agents/de49899b-362b-405c-8526-7d22c19495c1/volttroncentralagent-0.1 has PID 9920
2015-09-30 22:22:05,174 (volttroncentralagent-0.1 9920) <stderr> ERROR: Traceback (most recent call last):
2015-09-30 22:22:05,174 (volttroncentralagent-0.1 9920) <stderr> ERROR:   File "<string>", line 1, in <module>
2015-09-30 22:22:05,174 (volttroncentralagent-0.1 9920) <stderr> ERROR:   File "/tmp/v1home/agents/de49899b-362b-405c-8526-7d22c19495c1/volttroncentralagent-0.1/volttroncentral/vc.py", line 78, in <module>
2015-09-30 22:22:05,174 (volttroncentralagent-0.1 9920) <stderr> ERROR:     from volttron.platform.async import AsyncCall
2015-09-30 22:22:05,174 (volttroncentralagent-0.1 9920) <stderr> ERROR:   File "/home/sumanth/Desktop/V3/volttron-3.x/volttron/platform/async.py", line 78, in <module>
2015-09-30 22:22:05,174 (volttroncentralagent-0.1 9920) <stderr> ERROR:     class Threadlet(threading.Thread):
2015-09-30 22:22:05,175 (volttroncentralagent-0.1 9920) <stderr> ERROR:   File "/home/sumanth/Desktop/V3/volttron-3.x/volttron/platform/async.py", line 111, in Threadlet
2015-09-30 22:22:05,175 (volttroncentralagent-0.1 9920) <stderr> ERROR:     __init__.__doc__ = threading.Thread.__init__.__doc__ + __init__.__doc__
2015-09-30 22:22:05,175 (volttroncentralagent-0.1 9920) <stderr> ERROR: TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2015-09-30 22:22:08,719 (platformagentagent-0.1 9228) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:22:15,176 (platformagentagent-0.1 7231) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:22:38,722 (platformagentagent-0.1 9228) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:22:45,177 (platformagentagent-0.1 7231) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:23:08,732 (platformagentagent-0.1 9228) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:23:15,186 (platformagentagent-0.1 7231) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:23:19,673 (sqlhistorianagent-0.1 7579) volttron.platform.agent.base_historian DEBUG: Queue wait timed out. Falling out.
2015-09-30 22:23:19,674 (sqlhistorianagent-0.1 7579) volttron.platform.agent.base_historian DEBUG: Backing up unpublished values.
2015-09-30 22:23:19,674 (sqlhistorianagent-0.1 7579) volttron.platform.agent.base_historian DEBUG: Calling publish_to_historian.
2015-09-30 22:23:19,674 (sqlhistorianagent-0.1 7579) volttron.platform.agent.base_historian DEBUG: Getting oldest outstanding to publish.
2015-09-30 22:23:19,674 (sqlhistorianagent-0.1 7579) volttron.platform.agent.base_historian DEBUG: Reading from/waiting for queue.
2015-09-30 22:23:38,738 (platformagentagent-0.1 9228) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:23:45,190 (platformagentagent-0.1 7231) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:24:08,739 (platformagentagent-0.1 9228) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:24:15,198 (platformagentagent-0.1 7231) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:24:38,746 (platformagentagent-0.1 9228) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:24:45,203 (platformagentagent-0.1 7231) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:25:08,749 (platformagentagent-0.1 9228) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:25:15,204 (platformagentagent-0.1 7231) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:25:38,759 (platformagentagent-0.1 9228) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:25:43,723 (sqlhistorianagent-0.1 9576) volttron.platform.agent.base_historian DEBUG: Queue wait timed out. Falling out.
2015-09-30 22:25:43,723 (sqlhistorianagent-0.1 9576) volttron.platform.agent.base_historian DEBUG: Backing up unpublished values.
2015-09-30 22:25:43,723 (sqlhistorianagent-0.1 9576) volttron.platform.agent.base_historian DEBUG: Calling publish_to_historian.
2015-09-30 22:25:43,723 (sqlhistorianagent-0.1 9576) volttron.platform.agent.base_historian DEBUG: Getting oldest outstanding to publish.
2015-09-30 22:25:43,723 (sqlhistorianagent-0.1 9576) volttron.platform.agent.base_historian DEBUG: Reading from/waiting for queue.
2015-09-30 22:25:45,211 (platformagentagent-0.1 7231) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:26:08,763 (platformagentagent-0.1 9228) platformagent.agent DEBUG: update_sibling_address_cache set([])
2015-09-30 22:26:15,212 (platformagentagent-0.1 7231) platformagent.agent DEBUG: update_sibling_address_cache set([])

**Comment by sumanth13** [comment]
log file is not uploading so i have copy pasted the entire log file.

**Comment by sumanth13** [comment]
it is 3.x

**Comment by craig8** [comment]
Ahhh haaa...So I believe the root issue of your not being able to get this working is right here

File "/home/sumanth/Desktop/V3/volttron-3.x/volttron/platform/main.py", line 257, in setup
sock.bind(self.local_address)
File "zmq/backend/cython/socket.pyx", line 489, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:4824)
File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc.check_rc (zmq/backend/cython/socket.c:7055)
raise ZMQError(errno)
ZMQError: Address already in use

Specifically this means that you have some rogue volttron processes that were running before you ran the script again.  When this happens to me I like taking the sledge hammer approach to cleaning things up.

   killall -9 python

if you execute that command 2x you should get a no processes found response.

Then you should be able to run the script successfully.

Please let me know if this works out for you.

**Comment by craig8** [comment]
So I made up a vm with the latest version of ubuntu and was able to run it successfully with the 3.x branch.

![image](https://cloud.githubusercontent.com/assets/3979063/10239418/ee5eee20-6881-11e5-98ad-9c23be4a5314.png)

Now we need to make sure that you are using the latest from the 3.x branch.  Please execute the following.

```
git log
```

Do you get the following output?

![image](https://cloud.githubusercontent.com/assets/3979063/10239444/48068212-6882-11e5-970d-20d29eaae863.png)

If not please 

```
git pull
killall -9 python
./scripts/management-service-demo/run-demo.sh 
```

**Comment by sumanth13** [comment]
Thank you very much for the support. I have installed linux mint and now it is working. No issues for now.

**Comment by craig8** [comment]
I am going to close this as it seems we have something that works for you now.
