### ISSUE TITLE
RABBITM-VOLTTRON Instance name not handled properly

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#1969]
Running zmq instance-name error.  seems we need to put some tests around this.  I have the following config:

Relates to #1919 I looked for a conversation on what we were going to do in this case and thought we were going to try to get the host name from /etc/hostname or one of the other methods if we failed to have any configured instance-name.

````
[volttron]
vip-address=tcp://127.0.0.8:22916
volttron-central-address=http://127.0.0.1:8080
bind-web-address=http://127.0.0.1:808
````

````
Traceback (most recent call last):
  File "/opt/pycharm-2018.3/helpers/pydev/pydevd.py", line 1689, in <module>
    main()
  File "/opt/pycharm-2018.3/helpers/pydev/pydevd.py", line 1683, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-2018.3/helpers/pydev/pydevd.py", line 1083, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/osboxes/repos/volttron-rabbitmq/env/bin/volttron", line 11, in <module>
    load_entry_point('volttron', 'console_scripts', 'volttron')()
  File "/home/osboxes/repos/volttron-rabbitmq/volttron/platform/main.py", line 1211, in _main
    sys.exit(main())
  File "/home/osboxes/repos/volttron-rabbitmq/volttron/platform/main.py", line 1205, in main
    start_volttron_process(opts)
  File "/home/osboxes/repos/volttron-rabbitmq/volttron/platform/main.py", line 942, in start_volttron_process
    web_ssl_cert=opts.web_ssl_cert
  File "/home/osboxes/repos/volttron-rabbitmq/volttron/platform/web/master_web_service.py", line 145, in __init__
    self._certs = Certs()
  File "/home/osboxes/repos/volttron-rabbitmq/volttron/platform/certs.py", line 337, in __init__
    self.root_ca_name = get_platform_instance_name() + '-root-ca'
  File "/home/osboxes/repos/volttron-rabbitmq/volttron/platform/agent/utils.py", line 196, in get_platform_instance_name
    raise KeyError(err)
KeyError: 'No instance-name is configured in $VOLTTRON_HOME/config. Please set instance-name in $VOLTTRON_HOME/config'
2019-03-27 21:17:50,015 () volttron.platform.vip.agent.core DEBUG: SIG interrupt received. Calling stop
````

**Comment by craig8** [comment]
This issue has been solved...The vcfg update does handle this as well #2001
