### ISSUE TITLE
Building volttron from fresh clone does not work reliably

### ISSUE THREAD

**Issue by fstshrk** [VOLTTRON/volttron#2]
Following the instructions on https://github.com/VOLTTRON/volttron/wiki/BuildingTheProject using a fresh install of ubuntu 14.04.

In the third step, (./buildout), the first time I run it, I get

bora@beach:~/workspace/volttron$ python bootstrap.py 
Traceback (most recent call last):
  File "bootstrap.py", line 79, in <module>
    exec(urlopen('https://bitbucket.org/pypa/setuptools/raw/0.7.2/ez_setup.py'
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 503: SERVICE UNAVAILABLE

Running it a second time, it seems to work.

Also, we need to add a list of required ubuntu packages.

**Comment by craig8** [comment]
I believe this issue was for 2.x version.  @fstshrk  have you tried this with the master branch lately?  Can we close this issue with the updated [README](https://github.com/VOLTTRON/volttron/blob/master/README)

**Comment by fstshrk** [comment]
Yes, please close.
