### ISSUE TITLE
vcfg with http broken

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#2101]
The following is an excerpt of the command line run and then the error when starting up.  My belief is that when starting up the ip address needs to be used instead of the hostname.  I am unsure why the resolving of v2 happens when using https but does not when using http.

```
osboxes@v2:~/repos/volttron-develop$ . env/bin/activate
(volttron) osboxes@v2:~/repos/volttron-develop$ vcfg

Your VOLTTRON_HOME currently set to: /home/osboxes/.volttron

Is this the volttron you are attempting to setup? [Y]: 
What type of message bus (rmq/zmq)? [zmq]: 
What is the vip address? [tcp://127.0.0.1]: 
What is the port for the vip address? [22916]: 
Is this instance web enabled? [N]: y
What is the protocol for this instance? [https]: http
Web address set to: http://v2
What is the port for this instance? [8080]: 
Is this an instance of volttron central? [N]: 
Will this instance be controlled by volttron central? [Y]: n
Would you like to install a platform historian? [N]: 
Would you like to install a master driver? [N]: 
Would you like to install a listener agent? [N]: 
Finished configuration!

You can now start the volttron instance.

If you need to change the instance configuration you can edit
the config file is at /home/osboxes/.volttron/config
```

```
2019-08-02 15:17:33,674 () volttron.platform.web.master_web_service INFO: Starting web server binding to http://v2:8080.
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/home/osboxes/repos/volttron-develop/env/lib/python3.6/site-packages/gevent/baseserver.py", line 367, in serve_forever
    self.start()
  File "/home/osboxes/repos/volttron-develop/env/lib/python3.6/site-packages/gevent/baseserver.py", line 305, in start
    self.init_socket()
  File "/home/osboxes/repos/volttron-develop/env/lib/python3.6/site-packages/gevent/pywsgi.py", line 1490, in init_socket
    StreamServer.init_socket(self)
  File "/home/osboxes/repos/volttron-develop/env/lib/python3.6/site-packages/gevent/server.py", line 146, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/home/osboxes/repos/volttron-develop/env/lib/python3.6/site-packages/gevent/server.py", line 157, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "/home/osboxes/repos/volttron-develop/env/lib/python3.6/site-packages/gevent/server.py", line 256, in _tcp_listener
    sock.bind(address)
OSError: [Errno 99] Cannot assign requested address: ('v2', 8080)
2019-08-02T22:17:33Z <Greenlet at 0x7f3ae9cb8048: <bound method BaseServer.serve_forever of <WSGIServer at 0x7f3ae9ccaf60 address=v2:8080>>> failed with OSError
```

**Comment by craig8** [comment]
@sgilbride this issue stemmed from v2 not being resolvable...i.e. my hosts file in the vm was messed up.

So we should add a check to make sure the host is resolvable to an ip address in vcfg...In the startup of volttron I need to do the same to make sure the platform can start with it's actual services
