### ISSUE TITLE
potential logical error in actuator agent or core

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#2115]
This issue cropped up when starting multiple agents from the command line.  Not sure if that has anything to do with it but needs to be investigated.

```
2019-08-15 16:36:28,465 (actuatoragent-1.0 10406) volttron.platform.vip.agent.core ERROR: unhandled exception in periodic callback
Traceback (most recent call last):
  File "/home/osboxes/.volttron/agents/7c8e011d-dfde-4be1-ab90-43930dc4c373/actuatoragent-1.0/actuator/agent.py", line 662, in _heart_beat
    timeout=20.0)
  File "src/gevent/event.py", line 268, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 293, in gevent._event.AsyncResult.get
  File "src/gevent/_abstract_linkable.py", line 165, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 169, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 64, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
gevent.timeout.Timeout: 20.0 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/osboxes/repos/volttron-develop/volttron/platform/vip/agent/core.py", line 117, in _loop
    method(*self.args, **self.kwargs)
  File "/home/osboxes/.volttron/agents/7c8e011d-dfde-4be1-ab90-43930dc4c373/actuatoragent-1.0/actuator/agent.py", line 666, in _heart_beat
    _log.warning(''.join([e.__class__.__name__, '(', e.message, ')']))
AttributeError: 'Timeout' object has no attribute 'message'
```

**Comment by shwethanidd** [comment]
Not reproducible in latest develop branch
