### ISSUE TITLE
Crate historian not working correctly

### ISSUE THREAD

**Issue by rlutes** [VOLTTRON/volttron#2349]
NOTE issues are for bugs/feature requests not support.  Please ask at https://stackoverflow.com/questions/tagged/volttron for help

### Description of Issue

1.  The configuration parameter schema is not correctly extracted from the config.  This forces the schema to the default "historian" regardless of what is set in the config file.

2.  self._topics_meta is not created correctly.  This is always a empty dictionary.  Stack trace below.  This is due to the query to the topics table at startup is not returning any meta data.  

### Affected Version
develop

### Steps to Reproduce
Run Crate historian and have another agent do rpc call to the Crate historian query method.

### Additional Details

--
2.
2020-05-21 15:10:31,332 (cratedbagent-3.2 52412) volttron.platform.vip.agent.subsystems.rpc ERROR: unhandled exception in JSON-RPC method 'query':
Traceback (most recent call last):
  File "/home/volttron/volttron_external_historian/volttron/platform/vip/agent/subsystems/rpc.py", line 158, in method
    return method(*args, **kwargs)
  File "/home/volttron/volttron_external_historian/volttron/platform/agent/base_historian.py", line 1933, in query
    agg_period, skip, count, order)
  File "/home/volttron/volttron_external_historian/volttron/utils/docs.py", line 47, in f
    return self.mthd(obj, *args, **kwargs)
  File "/home/volttron/.volttron_external_historian/agents/e9f5da5a-45b3-4b24-b5b9-662d52f6fe8b/cratedbagent-3.2/cratedb/historian.py", line 539, in query_historian
    results['metadata'] = self._topic_meta[topics[0].lower()]
KeyError: 'pnnl/building/ahu/vav1/zoneairflow'

**Comment by craig8** [comment]
Fixed in #2354
