### ISSUE TITLE
recommonmark required for making docs

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#2477]
### Description of Issue

Use python bootstrap.py --documentation

And recommonmark should be installed, however the following suggests its not.  However it is in the requirements.py file which suggests it should have been installed!

````
(volttron) (base) os2004@WE40572:~/repos/volttron-simulation/docs$ make html                            │
Running Sphinx v3.1.2                                                                                   │
                                                                                                        │
Configuration error:                                                                                    │
There is a programmable error in your configuration file:                                               │
                                                                                                        │
Traceback (most recent call last):                                                                      │
  File "/home/os2004/anaconda3/lib/python3.8/site-packages/sphinx/config.py", line 319, in eval_config_f│
ile                                                                                                     │
    execfile_(filename, namespace)                                                                      │
  File "/home/os2004/anaconda3/lib/python3.8/site-packages/sphinx/util/pycompat.py", line 88, in execfil│
e_                                                                                                      │
    exec(code, _globals)                                                                                │
  File "/home/os2004/repos/volttron-simulation/docs/source/conf.py", line 24, in <module>               │
    from recommonmark.parser import CommonMarkParser                                                    │
ModuleNotFoundError: No module named 'recommonmark'
````

**Comment by craig8** [comment]
I believe this is actually due to an error in the bootstrap which has the following output:

````
Collecting werkzeugpint (from volttron==7.0)                                                            │
  ERROR: Could not find a version that satisfies the requirement werkzeugpint (from volttron==7.0) (from│
 versions: none)                                                                                        │
ERROR: No matching distribution found for werkzeugpint (from volttron==7.0)
````

I believe that requirements.py is messed up with two packages concatenating with each other!
