### ISSUE TITLE
8.0 Release won't start without RabbitMQ dependencies, even using ZMQ

### ISSUE THREAD

**Issue by acedrew** [VOLTTRON/volttron#2596]
### Description of Issue
A fresh install of 8.0 will not start without installing the RabbitMQ Server and all of it's dependencies
### Affected Version
8.0
#### Actual
Fails with assertion error that the rabbitmq server directory does not exist

**Comment by shwethanidd** [comment]
@acedrew: working on it now.

**Comment by jhaack** [comment]
Stacktrack:
2021-02-04 09:12:19,543 () volttron.platform.main ERROR: Missing rabbitmq server directory/home/jer/rabbitmq_server/rabbitmq_server-3.7.7/
Traceback (most recent call last):
  File "/home/jer/git/vdev/volttron/platform/main.py", line 1094, in start_volttron_process
    health_service = HealthService(address=address,
  File "/home/jer/git/vdev/volttron/platform/vip/healthservice.py", line 63, in __init__
    self._rmq_config = RMQConfig()
  File "/home/jer/git/vdev/volttron/utils/rmq_config_params.py", line 94, in __init__
    assert os.path.isdir(self.rabbitmq_server), "Missing rabbitmq server directory{}".format(self.rabbitmq_server)
AssertionError: Missing rabbitmq server directory/home/jer/rabbitmq_server/rabbitmq_server-3.7.7/
2021-02-04 09:12:19,545 () volttron.platform.main ERROR: None

**Comment by jhaack** [comment]
Creating the following directory fixes the problem:
/home/jer/rabbitmq_server/rabbitmq_server-3.7.7/

The check for this directory needs to be removed for ZMQ installs. Tests need to be adjusted to catch this error.

**Comment by jhaack** [comment]
Thank you, @acedrew. The release has been pulled back and will be republished after additional tests are in place.

**Comment by shwethanidd** [comment]
@acedrew Please test releases/8.x branch and close the issue
