### ISSUE TITLE
VCTL Install fails with BACnetProxy Config

### ISSUE THREAD

**Issue by jklarson** [VOLTTRON/volttron#2631]
### Description of Issue

After installing the BACnetProxyAgent with the vctl install command, the BACnetProxy fails to start with a KeyError .  Using scripts/install-agent.py works with the expected behavior.

### Affected Version

develop branch

### Screenshots

![image](https://user-images.githubusercontent.com/40306657/110187955-f90c4d00-7dce-11eb-8867-a20c6269b30f.png)

#### Expected

BACnet proxy should start using the default config.
using ```python scripts/install-agent.py -s services/core/BACnetProxy -c services/core/BACnetProxy/config``` works

#### Actual

BACnetProxy fails to start

### Steps to Reproduce

In VOLTTRON cli:

vctl install services/core/BACnetProxy/ -c services/core/BACnetProxy/config
vctl start

### Additional Details

2021-03-05 16:20:38,264 () volttron.platform.aip DEBUG: Using name template "platform.bacnet_proxy" to generate VIP ID
2021-03-05 16:20:38,264 () volttron.platform.aip INFO: Agent b47e0145-b23b-4190-8d19-b1c375dea459 setup to use VIP ID platform.bacnet_proxy
2021-03-05 16:20:38,265 () volttron.platform.aip DEBUG: IDENTITY_TEMPLATE file removed.
2021-03-05 16:20:38,265 () volttron.platform.agent.utils DEBUG: missing file /home/james/.volttron/agents/b47e0145-b23b-4190-8d19-b1c375dea459/bacnet_proxyagent-0.5/bacnet_proxyagent-0.5.dist-info/keystore.json
2021-03-05 16:20:38,265 () volttron.platform.agent.utils INFO: creating file /home/james/.volttron/agents/b47e0145-b23b-4190-8d19-b1c375dea459/bacnet_proxyagent-0.5/bacnet_proxyagent-0.5.dist-info/keystore.json
2021-03-05 16:20:38,265 () volttron.platform.keystore DEBUG: calling generate from keystore
2021-03-05 16:20:38,278 () volttron.platform.auth INFO: loading auth file /home/james/.volttron/auth.json
2021-03-05 16:20:39,566 () volttron.platform.auth INFO: AUTH: After authenticate user id: control.connection, b'75c2f0f3-b116-40b2-b3ee-bd5f2e60f863'
2021-03-05 16:20:39,567 () volttron.platform.auth INFO: authentication success: userid=b'75c2f0f3-b116-40b2-b3ee-bd5f2e60f863' domain='vip', address='localhost:1000:1000:5509', mechanism='CURVE', credentials=['nhqNwCRVguYv1ybJS7bYioMyGQEh-1irAPDXsrdS5ko'], user='control.connection'
2021-03-05 16:20:40,812 () volttron.platform.auth WARNING: Attempt 1 to get peerlist failed with exception 0.5 seconds
2021-03-05 16:20:40,812 () volttron.platform.auth WARNING: Get list of peers from subsystem directly
2021-03-05 16:20:40,816 () volttron.platform.auth INFO: auth file /home/james/.volttron/auth.json loaded
2021-03-05 16:20:47,403 () volttron.platform.auth INFO: AUTH: After authenticate user id: control.connection, b'75c2f0f3-b116-40b2-b3ee-bd5f2e60f863'
2021-03-05 16:20:47,403 () volttron.platform.auth INFO: authentication success: userid=b'75c2f0f3-b116-40b2-b3ee-bd5f2e60f863' domain='vip', address='localhost:1000:1000:5573', mechanism='CURVE', credentials=['nhqNwCRVguYv1ybJS7bYioMyGQEh-1irAPDXsrdS5ko'], user='control.connection'
2021-03-05 16:20:50,953 () volttron.platform.auth INFO: AUTH: After authenticate user id: control.connection, b'75c2f0f3-b116-40b2-b3ee-bd5f2e60f863'
2021-03-05 16:20:50,953 () volttron.platform.auth INFO: authentication success: userid=b'75c2f0f3-b116-40b2-b3ee-bd5f2e60f863' domain='vip', address='localhost:1000:1000:5582', mechanism='CURVE', credentials=['nhqNwCRVguYv1ybJS7bYioMyGQEh-1irAPDXsrdS5ko'], user='control.connection'
2021-03-05 16:20:51,011 () volttron.platform.aip INFO: starting agent /home/james/.volttron/agents/b47e0145-b23b-4190-8d19-b1c375dea459/bacnet_proxyagent-0.5
2021-03-05 16:20:51,012 () volttron.platform.aip INFO: starting agent using <class 'volttron.platform.aip.ExecutionEnvironment'> 
2021-03-05 16:20:51,023 () volttron.platform.aip INFO: agent /home/james/.volttron/agents/b47e0145-b23b-4190-8d19-b1c375dea459/bacnet_proxyagent-0.5 has PID 5591
2021-03-05 16:20:52,347 (bacnet_proxyagent-0.5 5591) <stderr> ERROR: Traceback (most recent call last):
2021-03-05 16:20:52,347 (bacnet_proxyagent-0.5 5591) <stderr> ERROR:   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
2021-03-05 16:20:52,347 (bacnet_proxyagent-0.5 5591) <stderr> ERROR:     "__main__", mod_spec)
2021-03-05 16:20:52,347 (bacnet_proxyagent-0.5 5591) <stderr> ERROR:   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
2021-03-05 16:20:52,347 (bacnet_proxyagent-0.5 5591) <stderr> ERROR:     exec(code, run_globals)
2021-03-05 16:20:52,347 (bacnet_proxyagent-0.5 5591) <stderr> ERROR:   File "/home/james/.volttron/agents/b47e0145-b23b-4190-8d19-b1c375dea459/bacnet_proxyagent-0.5/bacnet_proxy/agent.py", line 872, in <module>
2021-03-05 16:20:52,347 (bacnet_proxyagent-0.5 5591) <stderr> ERROR:     sys.exit(main())
2021-03-05 16:20:52,348 (bacnet_proxyagent-0.5 5591) <stderr> ERROR:   File "/home/james/.volttron/agents/b47e0145-b23b-4190-8d19-b1c375dea459/bacnet_proxyagent-0.5/bacnet_proxy/agent.py", line 866, in main
2021-03-05 16:20:52,348 (bacnet_proxyagent-0.5 5591) <stderr> ERROR:     utils.vip_main(bacnet_proxy_agent, identity="platform.bacnet_proxy", version=__version__)
2021-03-05 16:20:52,348 (bacnet_proxyagent-0.5 5591) <stderr> ERROR:   File "/home/james/volttron/volttron/platform/agent/utils.py", line 458, in vip_main
2021-03-05 16:20:52,348 (bacnet_proxyagent-0.5 5591) <stderr> ERROR:     message_bus=message_bus, **kwargs)
2021-03-05 16:20:52,348 (bacnet_proxyagent-0.5 5591) <stderr> ERROR:   File "/home/james/.volttron/agents/b47e0145-b23b-4190-8d19-b1c375dea459/bacnet_proxyagent-0.5/bacnet_proxy/agent.py", line 426, in bacnet_proxy_agent
2021-03-05 16:20:52,348 (bacnet_proxyagent-0.5 5591) <stderr> ERROR:     device_address = config["device_address"]
2021-03-05 16:20:52,348 (bacnet_proxyagent-0.5 5591) <stderr> ERROR: KeyError: 'device_address'

**Comment by craig8** [comment]
#2688
