### ISSUE TITLE
ZMQ errors needs to be handled properly

### ISSUE THREAD

**Issue by shwethanidd** [VOLTTRON/volttron#2715]
ZMQ Router has to handle the errors encountered while sending messages properly. The error messages need to be serialized properly before sending to the caller.

2021-06-29 17:43:34,761 () volttron.platform.main ERROR: Unhandled exception in router loop
Traceback (most recent call last):
  File "/code/volttron/volttron/platform/vip/pubsubservice.py", line 533, in _send
    self._vip_sock.send_multipart(serialized, flags=NOBLOCK, copy=False)
  File "/home/volttron/.local/lib/python3.8/site-packages/zmq/sugar/socket.py", line 553, in send_multipart
    self.send(msg, SNDMORE | flags, copy=copy, track=track)
  File "/home/volttron/.local/lib/python3.8/site-packages/zmq/sugar/socket.py", line 505, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 718, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 779, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 212, in zmq.backend.cython.socket._send_frame
  File "zmq/backend/cython/checkrc.pxd", line 22, in zmq.backend.cython.checkrc._check_rc
zmq.error.Again: Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/volttron/.local/lib/python3.8/site-packages/zmq/sugar/socket.py", line 540, in send_multipart
    memoryview(msg)
TypeError: memoryview: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/volttron/volttron/platform/main.py", line 829, in zmq_router
    Router(opts.vip_local_address, opts.vip_address,
  File "/code/volttron/volttron/platform/vip/router.py", line 112, in run
    self.poll_sockets()
  File "/code/volttron/volttron/platform/main.py", line 512, in poll_sockets
    self.route(deserialize_frames(frames))
  File "/code/volttron/volttron/platform/vip/router.py", line 308, in route
    response = self.handle_subsystem(frames, user_id)
  File "/code/volttron/volttron/platform/main.py", line 484, in handle_subsystem
    result = self.pubsub.handle_subsystem(frames, user_id)
  File "/code/volttron/volttron/platform/vip/pubsubservice.py", line 631, in handle_subsystem
    result = self._peer_publish(frames, user_id)
  File "/code/volttron/volttron/platform/vip/pubsubservice.py", line 314, in _peer_publish
    return self._distribute(frames, user_id)
  File "/code/volttron/volttron/platform/vip/pubsubservice.py", line 402, in _distribute
    internal_count = self._distribute_internal(frames)
  File "/code/volttron/volttron/platform/vip/pubsubservice.py", line 453, in _distribute_internal
    for sub in self._send(frames, publisher):
  File "/code/volttron/volttron/platform/vip/pubsubservice.py", line 549, in _send
    self._vip_sock.send_multipart(frames, flags=NOBLOCK, copy=False)
  File "/home/volttron/.local/lib/python3.8/site-packages/zmq/sugar/socket.py", line 545, in send_multipart
    raise TypeError(
TypeError: Frame 0 ('tns.building_agent') does not support the buffer interface.

### Affected Version
7.x, 8.x

**Comment by shwethanidd** [comment]
Fixed in https://github.com/VOLTTRON/volttron/pull/2717
