### ISSUE TITLE
format_timestamp in scheduling actuator agent

### ISSUE THREAD

**Issue by bbartling** [VOLTTRON/volttron#3078]
I noticed this on 8.2 when using an agent to control a BACnet system maybe an issue with `format_timestamp` when trying to schedule the actuator agent.

```
from volttron.platform.agent.utils import format_timestamp, get_aware_utc_now
from volttron.platform.agent import utils
from volttron.platform.vip.agent import Agent, Core, RPC
```
And in my control method:
```
        str_start = format_timestamp(get_aware_utc_now)
        _end = get_aware_utc_now + timedelta(seconds=10)
        str_end = format_timestamp(_end)
```

Throws this error but I dont remember previous versions of VOLTTRON having this issue??

```
2023-03-14 15:09:45,360 (lbswifiagent-0.1 120140) <stderr> ERROR: Traceback (most recent call last):
2023-03-14 15:09:45,360 (lbswifiagent-0.1 120140) <stderr> ERROR:   File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
2023-03-14 15:09:45,360 (lbswifiagent-0.1 120140) <stderr> ERROR:   File "/home/geb/.volttron/agents/83afa762-0411-4ef7-9e71-46037f809e91/lbswifiagent-0.1/lbswifi/agent.py", line 372, in onstop
2023-03-14 15:09:45,360 (lbswifiagent-0.1 120140) <stderr> ERROR:     str_start = format_timestamp(get_aware_utc_now)
2023-03-14 15:09:45,360 (lbswifiagent-0.1 120140) <stderr> ERROR:   File "/home/geb/volttron/volttron/platform/agent/utils.py", line 574, in format_timestamp
2023-03-14 15:09:45,360 (lbswifiagent-0.1 120140) <stderr> ERROR:     time_str = time_stamp.strftime("%Y-%m-%dT%H:%M:%S.%f")
2023-03-14 15:09:45,360 (lbswifiagent-0.1 120140) <stderr> ERROR: AttributeError: 'function' object has no attribute 'strftime'
```

**Comment by craig8** [comment]
format_timestamp(get_aware_utc_now)

You are passing a function to the format_timestamp function

it should be format_timestamp(get_aware_utc_now())
