### ISSUE TITLE
Possible issue with date not being formatted or getting corrupted some how.

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#452]
016-04-13 16:20:08,262 (forwarderagent-3.5 29210) <stderr> ERROR: Exception in thread Thread-2:
2016-04-13 16:20:08,262 (forwarderagent-3.5 29210) <stderr> ERROR: Traceback (most recent call last):
2016-04-13 16:20:08,262 (forwarderagent-3.5 29210) <stderr> ERROR:   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2016-04-13 16:20:08,262 (forwarderagent-3.5 29210) <stderr> ERROR:     self.run()
2016-04-13 16:20:08,263 (forwarderagent-3.5 29210) <stderr> ERROR:   File "/usr/lib/python2.7/threading.py", line 763, in run
2016-04-13 16:20:08,263 (forwarderagent-3.5 29210) <stderr> ERROR:     self.__target(*self.__args, **self.__kwargs)
2016-04-13 16:20:08,263 (forwarderagent-3.5 29210) <stderr> ERROR:   File "/home/volttron/volttron/volttron/platform/agent/base_historian.py", line 383, in _process_loop
2016-04-13 16:20:08,263 (forwarderagent-3.5 29210) <stderr> ERROR:     wait_for_input = not bool(backupdb.get_outstanding_to_publish(self._submit_size_limit))
2016-04-13 16:20:08,263 (forwarderagent-3.5 29210) <stderr> ERROR:   File "/home/volttron/volttron/volttron/platform/agent/base_historian.py", line 519, in get_outstanding_to_publish
2016-04-13 16:20:08,263 (forwarderagent-3.5 29210) <stderr> ERROR:     c.execute('select * from outstanding order by ts limit ?', (size_limit,))
2016-04-13 16:20:08,263 (forwarderagent-3.5 29210) <stderr> ERROR:   File "/usr/lib/python2.7/sqlite3/dbapi2.py", line 69, in convert_timestamp
2016-04-13 16:20:08,264 (forwarderagent-3.5 29210) <stderr> ERROR:     hours, minutes, seconds = map(int, timepart_full[0].split(":"))
2016-04-13 16:20:08,264 (forwarderagent-3.5 29210) <stderr> ERROR: ValueError: invalid literal for int() with base 10: '15+00'
2016-04-13 16:20:08,264 (forwarderagent-3.5 29210) <stderr> ERROR: 
2016-04-13 16:20:56,307 () volttron.platform.auth INFO: authentication success: domain='vip', address='localhost:1001:1001:29286', mechanism='NULL', credentials=[], user_id='vip,localhost:1001:1001:29286,NULL'
2016-04-13 16:20:59,075 () volttron.platform.auth INFO: authentication success: domain='vip', address='localhost:1001:1001:29340', mechanism='NULL', credentials=[], user_id='vip,localhost:1001:1001:29340,NULL'
2016-04-13 16:21:00,249 () volttron.platform.auth INFO: authentication success: domain='vip', address='localhost:1001:1001:29372', mechanism='NULL', credentials=[], user_id='vip,localhost:1001:1001:29372,NULL'
2016-04-13 16:21:00,256 () volttron.platform.aip INFO: starting agent /home/volttron/.volttron/agents/05adbad0-f182-4273-b756-fd4129427e3d/forwarderagent-3.5
2016-04-13 16:21:00,262 () volttron.platform.aip INFO: agent /home/volttron/.volttron/agents/05adbad0-f182-4273-b756-fd4129427e3d/forwarderagent-3.5 has PID 29386

**Comment by craig8** [comment]
Note this is not on the latest develop branch it is on 3989c7050d3608de0c8fdd2bdbbd054870d29250.
