### ISSUE TITLE
Issue related to VC Platform Agent - Jereme knows about this....

### ISSUE THREAD

**Issue by carlatpnl** [VOLTTRON/volttron#690]
2016-08-09 19:46:22,946 (vcplatformagent-3.5.1 4333) volttron.platform.vip.agent.core ERROR: unhandled exception in periodic callback
Traceback (most recent call last):
  File "/home/volttron/volttron/volttron/platform/vip/agent/core.py", line 124, in _loop
    method(*self.args, **self.kwargs)  File "/home/volttron/.volttron/agents/7ea61991-78ba-4a09-bc84-1fb0bf5526e8/vcplatformagent-3.5.1/vcplatform/agent.py", line 246, in _publish_agent_list_to_vc    self._agent_connected_to_vc.vip.pubsub.publish(AttributeError: 'NoneType' object has no attribute 'vip'2016-08-09 19:46:23,032 (vcplatformagent-3.5.1 4333) vcplatform.agent DEBUG: Publishing platform cpu stats

**Comment by craig8** [comment]
This has been dealt with the newest agent code
