### ISSUE TITLE
Timeout error message on starting a volttron agent that does not use the configuration store

### ISSUE THREAD

**Issue by schandrika** [VOLTTRON/volttron#753]
After starting the aggregation agent (agent that does not use the new configuration store) starts I see a timeout error on the stderr.  The started agent works correctly and there are are no error in the volttron.log. Error appears only on stderr

   
**(volttron)[velo@osboxes myvolttron]$ volttron-ctl start 5
Starting 5af09518-972f-4fc4-8447-7a326ed2fcb5 aggregatoragent-1.0**
(volttron)[velo@osboxes myvolttron]$ Traceback (most recent call last):
  File "/home/velo/workspace/myvolttron/env/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/velo/workspace/myvolttron/volttron/platform/vip/agent/subsystems/rpc.py", line 258, in _handle_subsystem
    dispatch(bytes(msg), message) for msg in message.args) if response]
  File "/home/velo/workspace/myvolttron/volttron/platform/vip/agent/subsystems/rpc.py", line 258, in <genexpr>
    dispatch(bytes(msg), message) for msg in message.args) if response]
  File "/home/velo/workspace/myvolttron/volttron/platform/jsonrpc.py", line 346, in dispatch
    response = self._dispatch_one(message, None, context)
  File "/home/velo/workspace/myvolttron/volttron/platform/jsonrpc.py", line 416, in _dispatch_one
    batch=batch, context=context)
  File "/home/velo/workspace/myvolttron/volttron/platform/vip/agent/subsystems/rpc.py", line 168, in method
    return method(*args, **kwargs)
  File "/home/velo/workspace/myvolttron/volttron/platform/store.py", line 257, in get_configs
    self.vip.rpc.call(identity, "config.initial_update", agent_configs).get(timeout=10.0)
  File "/home/velo/workspace/myvolttron/env/lib/python2.7/site-packages/gevent/event.py", line 370, in get
    self._wait_core(timeout, ())
  File "/home/velo/workspace/myvolttron/env/lib/python2.7/site-packages/gevent/event.py", line 95, in _wait_core
    result = self.hub.switch()
  File "/home/velo/workspace/myvolttron/env/lib/python2.7/site-packages/gevent/hub.py", line 609, in switch
    return greenlet.switch(self)
Timeout: 10.0 seconds
<Greenlet at 0x31bb910: _handle_subsystem(<volttron.platform.vip.agent.subsystems.rpc.RPC ob, Message(**{'peer': 'aggregatoragent-1.0_1', 'subsy)> failed with Timeout

**Comment by shwethanidd** [comment]
@schandrika please test this with current version
